version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db && 
              python manage.py migrate && 
              python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=postgresqldb
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=secretpassword
      - REDIS_PORT=6379
      - REDIS_HOST=redisserver
    depends_on: 
      - postgresqldb
      - redisserver

  redisserver:
    image: redis:6.2
    volumes:
      - ./redisconf:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports: 
      - "6379:6379"

  postgresqldb:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
    ports: 
      - "5432:5432"